### ISSUE TITLE
What would be the best way to add support for my library drbl-peer? plugins?

### ISSUE THREAD

**Issue by elico** [coredns/coredns.io#125]
I wrote a golang library named https://github.com/elico/drbl-peer
and I was thinking about a way to integrate this library with coredns when it's in proxy mode.

The idea is that the library will first process the A/AAAA queries and will return a specific "blackhole" ip that will block access to specific sites based on public blacklists in real-time.

**Comment by fturib** [comment]
@elico : I think you should move the issue to https://github.com/coredns/coredns
(this coredns/coredns.io repo is dedicated to the website coredns.io)
