### ISSUE TITLE
In high load Kubernetes containers doesn't use /etc/resolv.conf file.

### ISSUE THREAD

**Issue by f9777** [coredns/coredns.io#176]
What happened:
Container can't append search names from resolv.conf file for looked service in high load.Instead it sends the naked hostname as a questions to core-dns.

What you expected to happen:
For example , if I want to look for 'ms-hostname' service, I want it to send question like 'ms-hostname.default.svc.cluster.local.But instead in 100 requests, one of the requests is sent like 'ms-hostname'

Environment:

Kubernetes version (use kubectl version):
1.14

Cloud provider or hardware configuration:
AWS EKS

OS (e.g: cat /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Kernel (e.g. uname -a):
Linux frankfurt-ms-users-1-v1-d594c7bd7-gcwx4 4.14.154-128.181.amzn2.x86_64 #1 SMP Sat Nov 16 21:49:00 UTC 2019 x86_64 GNU/Linux

Network plugin and version (if this is a network-related bug):
config map :

Name: coredns
Namespace: kube-system
Labels: eks.amazonaws.com/component=coredns
k8s-app=kube-dns
Annotations: kubectl.kubernetes.io/last-applied-configuration:
{"apiVersion":"v1","data":{"Corefile":".:53 {\n errors\n health\n kubernetes cluster.local in-addr.arpa ip6.arpa {\n pods in...

Data
Corefile:
.:53 {
errors
health
kubernetes cluster.local in-addr.arpa ip6.arpa {
pods insecure
upstream
fallthrough in-addr.arpa ip6.arpa
}
prometheus :9153
proxy . /etc/resolv.conf
cache 30
}

**Comment by stp-ip** [comment]
This is the repo for the website at coredns.io and not for user specific issues. Please take a look at the issues at github.com/coredns/coredns/issues instead.
