### ISSUE TITLE
Use ISO dates within theme

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns.io#182]
* last modified
* blog dates
etc.

**Comment by stp-ip** [comment]
Is this something we want. I feel like CoreDNS is international enough to warrant just going with ISO formatted dates.

**Comment by miekg** [comment]
yes of course, there is only one way to display dates - don't even know what we do right now.

**Comment by stp-ip** [comment]
We don't do ISO so that's why I ran over this. Will open a PR.
