### ISSUE TITLE
Switch fully to Netlify

### ISSUE THREAD

**Issue by stp-ip** [coredns/coredns.io#185]
This is just a tracking and coordination issue, once we decide to switch beta.coredns.io to either coredns.io or about.coredns.io.

Sidenote. Netlify can redirect all incoming requests form coredns.io to about.coredns.io including TLS, if that's something we want.

Let me know if/when/how/what.

**Comment by stp-ip** [comment]
Any thoughts on switching? cc @miekg 
Any issues with the setup?

Current owners of the netlify account:
@caniszczyk Luc Perkins and me.
Happy to add any other maintainer to this, but overall all should be manageable from this repo.

**Comment by stp-ip** [comment]
Sidenote. 
Would love to have the switch done and use about.coredns.io so we can use the plain domain for helpful redirects later on, but that's not a blocker. Happy to prepare this aka the redirects via netlify.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Switch ful..." ]
>Any thoughts on switching? cc @miekg
>Any issues with the setup?
>
>Current owners of the netlify account:
>@caniszczyk Luc Perkins and me.
>Happy to add any other maintainer to this, but overall all should be manageable from this repo.

I think that's fine for now. It's only me that controls the DNS which may be problematic
at some point.

I'll flip the URL later today and then will remove the old website and setup later this
week.

Thanks for pushing this forward!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Switch ful..." ]
>Any thoughts on switching? cc @miekg
>Any issues with the setup?
>
>Current owners of the netlify account:
>@caniszczyk Luc Perkins and me.
>Happy to add any other maintainer to this, but overall all should be manageable from this repo.

I need an `A` and `AAAA` address for the new site (there can be multiple), so that the
apex also resolves to netifly, i.e. `coredns.io` without `www`

**Comment by stp-ip** [comment]
Will prepare the redirects from coredns.io/* to about.coredns.io as well as getting you the IPs. Special CDN used for cncf I guess so needs asking.

**Comment by stp-ip** [comment]
Netlify got back to me. The CNCF has different settings:

IP: 104.198.14.52
CNAME: cncf.netlifyglobalcdn.com

One issue, which I'm trying to clear up is IPv6 support. Seems like Netlify doesn't have broad support or mostly no support for IPv6.

We can hold back till I get a final response on IPv6 support or we can add the DNS records before.

**Comment by stp-ip** [comment]
Ping me beforehand so I can make sure all certs are getting provisioned and can clear any caches that prevent that.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Switch ful..." ]
> Seems like Netlify doesn't have broad support or mostly no support for IPv6.

really? #sigh

/Miek

--
Miek Gieben

**Comment by stp-ip** [comment]
They are using Google TCP LBs without IPv6 termination and various cloud instances on multiple providers with only 2/3s supporting IPv6.

So no IPv6 with Netlify for now. I'm being the annoying pushing user now and will see what wiggle room we can get in terms of IPv6 support sooner than later.

Ready for the switch, if we can live with no IPv6 support.

**Comment by stp-ip** [comment]
Quoting support:
"So - TL;DR - we have no plans for an ipv6 load balancer today."

Translation:
IPv4 works and we have no intention of adding full IPv6 support anytime soon.

Gotta say hearing that from a "modern" provider is kinda disheartening :-1:

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Switch ful..." ]
>Quoting support:
>"So - TL;DR - we have no plans for an ipv6 load balancer today."
>
>Translation:
>IPv4 works and we have no intention of adding full IPv6 support anytime soon.
>
>Gotta say hearing that from a "modern" provider is kinda disheartening :-1:

I'm actually pretty upset by this and basically don't want to give us our business (even
though cncf pays).

In CoreDNS IPv6 is a first class citizen, I don't want to host on a service that basically
doesn't understand how the internet works...

**Comment by stp-ip** [comment]
Sorta agree on that note. The positive side would be the improved process.

Most of this seems to stem from their usage of Cloud and Cloud services not caring that much about IPv6 yet. They did have their own anycast network and would have hoped they understood networking, but seems like they switched to less own infrastructure to more generic Cloud infra.

Happy to hold off on the grounds of principal, but also would be glad to have it done.

Interesting tidbit. Kubernetes.io is not available under IPv6 at all. So what a statement from CNCF.

@caniszczyk thoughts on this?

**Comment by SuperQ** [comment]
Reviving this thread,

I made a proposal to @miekg that we could solve the v4/v6 issue by putting a CDN that supports v6 in front of Netlify.

I was going to suggest we give Fastly a try. They have an [open source program](https://www.fastly.com/open-source/) for sponsoring accounts.

**Comment by stp-ip** [comment]
Happy to help even with limited time :baby: ;)

**Comment by SuperQ** [comment]
I've opened a ticket with the CNCF to get us a Fastly account.

**Comment by stp-ip** [comment]
In terms of automatic pushing to netlify and stuff being pushed into the repo: https://github.com/coredns/coredns.io/commit/d77d4d1879216a01bcefe90c584869705fd972d1
I have this on my to too long fix list for some time. Should be failing due to some changes to github actions.
