### ISSUE TITLE
Undocumented: federation

### ISSUE THREAD

**Issue by imba-tjd** [coredns/coredns.io#187]
**What would you like to be added**:

A section of federation in `https://coredns.io/explugins/`

**Why is this needed**:

It should be found in the external plugins doc.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns.io] Undocumented: ..." ]
>**What would you like to be added**:
>
>A section of federation in `https://coredns.io/explugins/`
>
>**Why is this needed**:
>
>It should be found in the external plugins doc.

federation is deprecated and removed here as we track master.

Having docs for older version up is a handy, but we haven't come around doing that.

**Comment by imba-tjd** [comment]
I don't quite understand.
I saw `federation:github.com/coredns/federation` in `plugin.cfg` but didn't see a doc, so I opened this issue.
If current doc is expected, feel free to close this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Undocument..." ]
>I don't quite understand.
>I saw `federation:github.com/coredns/federation` in `plugin.cfg` but didn't see a doc, so I opened this issue.
>If current doc is expected, feel free to close this.

Ah you're right, I see it; yes we should do/fix that.

**Comment by imba-tjd** [comment]
I think this can be closed. That plugin is not built by default now.
