### ISSUE TITLE
Add openshift/coredns-mdns plugin to the external plugins page

### ISSUE THREAD

**Issue by displague** [coredns/coredns.io#194]
https://github.com/openshift/coredns-mdns is not included in https://coredns.io/manual/explugins/

**Comment by displague** [comment]
I may create this PR myself, the issue stands as a placeholder.  I don't know how to work with coredns plugins outside of the instructions to compile the plugin in.

My interest in this extends from https://github.com/kubernetes-sigs/external-dns/issues/1604.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns.io] Add openshift/..." ]
>https://github.com/openshift/coredns-mdns is not included in https://coredns.io
>/manual/explugins/

I you want to add it you need to submit a PR that contains the readme + some metadata
