### ISSUE TITLE
website render issue on Windows 7 + Chrome 78*

### ISSUE THREAD

**Issue by neolit123** [coredns/coredns.io#198]
**What happened**:
hello, i was trying to read the release notes for the latest release on the website:
https://coredns.io/2020/06/15/coredns-1.7.0-release/
the page is not rendering correctly for me on Chrome.

---

screenshot1

![coredns-page0](https://user-images.githubusercontent.com/331852/86245711-8a794e80-bbb2-11ea-97b0-d8bf1dc395ce.jpg)

---

screenshot2

![coredns-page](https://user-images.githubusercontent.com/331852/86245387-0e7f0680-bbb2-11ea-8a94-35b25ca380fd.jpg)

---

**What you expected to happen**:
the page renders correctly.

**How to reproduce it (as minimally and precisely as possible)**:
a colleague of mine said that they don't have the same issue.
(possibly a newer version of Chrome + Windows 10)

**Anything else we need to know?**:
- renders fine under Firefox.

if i "inspect" the page under Chrome and remove the usage of the "Lato" font the page renders correctly:
![coredns-page-lato](https://user-images.githubusercontent.com/331852/86246090-1d19ed80-bbb3-11ea-9f38-15cda0d83a13.jpg)

**Environment**:
- Windows 7 64bit
- Chrome 78.0.4050.0

**Comment by miekg** [comment]
shouldn't a browser use another font if the first one is unavailable?

**Comment by neolit123** [comment]
AFAIK (not a web developer though), it if Lato is not installed on the system it should fallback to the second entry in the list, although that does not seem to happen.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] website re..." ]
>AFAIK (not a web developer though), it if Lato is not installed on the system
>it should fallback to the second entry in the list, although that does not seem
>to happen.

yes, that mimics what I undertand here; hence the super generic fallback.

I don't have windows (and certainly not windows 7), so I can't check

**Comment by neolit123** [comment]
i just tried on a Windows 10 machine that doesn't have Lato in \Windows\Fonts and it seems to work fine.

if i modify `font-family: Lato, sans-serif` to be e.g. `font-family: Foo, sans-serif` the fallback works, which tells me that "Lato" might be installed somehow, but not rendering properly. or maybe this version of Chrome thinks it's installed.

i know Slack uses Lato, but it does not install the font and just has it in it's resource folder.

i'm going to close this ticket given this works on my other Windows machine. this might be a weird bug with the Chrome / Windows 7 combination.

thanks!
