### ISSUE TITLE
need redesign

### ISSUE THREAD

**Issue by miekg** [coredns/coredns.io#2]
Now that we have a logo and are in cnfc we should redesign the wesite and add docs etc. etc.

Pref. this would still be hugo generated (and static). We should sketch out some ideas.

**Comment by miekg** [comment]
I'm pondering to use https://themes.gohugo.io/kube/ and merge the blog and main coredns.io site into one.
Seems something like https://imperavi.com/kube/docs/ could be used to describe the plugins and their usage

**Comment by johnbelamaric** [comment]
Looks nice. We should tweak it to match our logo though.

**Comment by miekg** [comment]
yep :-)

I'll whip something up - so we can check it out.

**Comment by miekg** [comment]
Pushing the new site in.
