### ISSUE TITLE
remove potential mem overcommitment 

### ISSUE THREAD

**Issue by rdxmb** [coredns/coredns.io#201]
When initializing the kubernetes-cluster with kubeadm, the resource-request and -limit for coredns differs. That can cause to mem overcommitment and oom-killed pods in the cluster.

In my case:

syslog:
```
[...]
[Mon Jul 13 04:07:15 2020] Memory cgroup out of memory: Kill process 48615 (mongod) score 1954 or sacrifice child
[...]
```

```
kubectl describe node drei
[...]
  kube-system                   coredns-66bff467f8-fcx9g               100m (5%)     0 (0%)      70Mi (0%)        170Mi (1%)       57d
[...]
  memory             16518324992 (98%)  16623182592 (99%)
```

My proposal is to set the limits to the same size as the requests.

**Comment by miekg** [comment]
this is the wrong repo for this request. And coredns org is probably also wrong.

**Comment by rdxmb** [comment]
Oh, I am sorry. What would be the right repo for that? @miekg

**Comment by chrisohaver** [comment]
> What would be the right repo

It would be the repo for whatever tool you use to provision your cluster. More precisely, whatever tool defines the coredns Deployment.

**Comment by rdxmb** [comment]
>  More precisely, whatever tool defines the coredns Deployment.
Hm, not easy to say :thinking: 

> It would be the repo for whatever tool you use to provision your cluster. 
This is `kubeadm init`. I will see if I find the right repository for that ...

**Comment by chrisohaver** [comment]
It's kubeadm, every k8s deployment tool decides independently how to configure the CoreDNS deployment.

kubeadm lives in https://github.com/kubernetes/kubernetes.

**Comment by rdxmb** [comment]
@chrisohaver thanks :+1:
