### ISSUE TITLE
Docs: DNS record types without file plugin RFC 1035 zone file

### ISSUE THREAD

**Issue by polarathene** [coredns/coredns.io#202]
While a useful plugin(`file`), it's not particularly nice to manage that kind of file manually. The `hosts` plugin works nicely for mapping an FQDN query to an IP, but lacks the ability to specify record types like MX or TXT?

The only other alternatives I've seen are sourcing from external software like Unbound, Redis, etc.

[dnsmasq for example](https://unix.stackexchange.com/a/478672):

```
# Define the zone
auth-zone=example.com
# Set SOA record
auth-soa=12345678,admin.example.com
# Set A record
address=/www.example.com/10.2.3.4
# Set MX record
mx-host=example.com,www.example.com,10
# Set TXT record
txt-record=_acme-challenge.www.example.com,f0o...bar
```

Or with RFC 1035, MX records from zone file for using with mailgun can be([RFC 1035 - Section 5.1 Format](https://tools.ietf.org/html/rfc1035#section-5.1) rules to be aware of):

```
mg		IN MX	10 mxa.mailgun.org.
mg		IN MX	10 mxb.mailgun.org.
mg		IN TXT	"v=spf1 include:mailgun.org ~all"
```

Would there be a way to support such within the Corefile? (different record types, not the various formats supported by RFC 1035) 

A plugin directive responding with record types? Currently `hosts`  only supports `A`, `AAAA`, and `PTR` records. A similar plugin could probably extend that for handling other records? Or is this not something CoreDNS is suitable for and should be outsourced elsewhere as it seems to be encouraged?

I think the `template` plugin [tries to show an example of doing this](https://coredns.io/plugins/template/#resolve-a-and-mx-records-for-ip-templates-in-example) but it's rather verbose looking.

**Comment by miekg** [comment]
closing in favor of #4130
