### ISSUE TITLE
Zombie page in /plugins

### ISSUE THREAD

**Issue by HsuanTingLu** [coredns/coredns.io#217]
I believe https://coredns.io/plugins/proxy/ should be taken down since it's been renamed to `forward`
It's not in `coredns.io/content/plugins/` but somehow the website still serves this page.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns.io] Zombie page in..." ]
>I believe https://coredns.io/plugins/proxy/ should be taken down since it's
>been renamed to forward
>It's not in coredns.io/content/plugins/ but somehow the website still serves
>this page.

yep, odd. Think hugo doesn't clear what in the html dir.

anyway, gone now

**Comment by HsuanTingLu** [comment]
Just found out that there is more:
- https://coredns.io/plugins/federation/

A scan in the generated files can catch all of them,
but zombie pages doesn't matter that much, probably not worth the hassle.
It's just kind of confusing when newcomers are wandering through the docs and be lead to these pages.

**Comment by HsuanTingLu** [comment]
By the way I found `https://coredns.io/plugins/proxy/` when looking for DNS-over-HTTPS setups to use for Google DNS,
it seem that `forward` support only `dns://` and `tls://`, do you have any pointers on how can I achieve that?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Zombie pag..." ]
>By the way I found https://coredns.io/plugins/proxy/ when looking for
>DNS-over-HTTPS setups to use for Google DNS,
>it seem that forward support only dns:// and tls://, do you have any pointers
>on how can I achieve that?

it can't and noone has built a https forwarder yet

**Comment by HsuanTingLu** [comment]
okay 

> [ Quoting <notifications@github.com> in "Re: [coredns/coredns.io] Zombie pag..." ]
> By the way I found https://coredns.io/plugins/proxy/ when looking for DNS-over-HTTPS setups to use for Google DNS, it seem that forward support only dns:// and tls://, do you have any pointers on how can I achieve that?
> it can't and noone has built a https forwarder yet

okay
thanks for the reply
I'll try to work something out
