### ISSUE TITLE
Broken link to source for the metrics plugin as of November 10th 2021

### ISSUE THREAD

**Issue by SerenaTiede-Zen** [coredns/coredns.io#242]
Preface not sure if this is the correct repo to report a bug with the website.

When clicking the link for the source of the metrics plugin I get a 404 error on github. The link on the website is `https://github.com/coredns/coredns/tree/master/plugin/prometheus` when it should be `https://github.com/coredns/coredns/tree/master/plugin/metrics`. 

Expected behavior:

clicking on the source link would take me to the source of the metrics plugin

What happened:

I was taken to a 404 page on github

Steps to reproduce:

1. Go to the metrics plugin documentation [here](https://coredns.io/plugins/metrics/)
2. Click on the Source hyperlink (link is https://github.com/coredns/coredns/tree/master/plugin/prometheus)

I think the html template for the theme might be the issue as seen below https://github.com/coredns/coredns.io/blob/1360d008fa3f4501f4f61a59d5acdf22d724b6b5/themes/coredns/layouts/section/plugins.html#L33-L35

Is that the title of the page is prometheus so the link you to `https://github.com/coredns/coredns/tree/master/plugin/prometheus` instead of `https://github.com/coredns/coredns/tree/master/plugin/metrics`. 

It might make sense use the base path for the source link as the cannonical source footer as seen here

https://github.com/coredns/coredns.io/blob/1360d008fa3f4501f4f61a59d5acdf22d724b6b5/themes/coredns/layouts/partials/source.html#L3-L6

**Comment by zouyee** [comment]
Would you mind to fix it?

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "Re: [coredns/coredns.io] Broken lin..." ]
>Would you mind to fix it?

I looked a bit, but can't really find a quick fix in the hugo stuff - the original of the
issue is that prometheus/metrics point to the same pluging.
