### ISSUE TITLE
Reverse plugin mention still present 

### ISSUE THREAD

**Issue by outout14** [coredns/coredns.io#260]
Following PR #135 which dates from 2019, the mention of the deprecated ``reverse`` plugin is still present in the documentation at the URL https://coredns.io/plugins/reverse/ 

This URL appears at the top of search results when searching for keywords ``coredns, reverse dns`` and provides misleading information. 

Since this page is not present in the source code of this repository, why is it still accessible?

**Comment by chrisohaver** [comment]
Nothing in the site links to it.  Though, it may still be indexed in search engines from when it was linked to.  Or there may be and old blog entry or two that point to the old plugin.

I suppose it's an artifact of how the web server is updated - new files are copied over old files, but deleted files remain.

Don't know if there is an easy way to automatically clean these up, or if it needs to be done manually. (I don't administer the web server)

**Comment by Feder1co5oave** [comment]
the linked URL now correctly returns 404. Can wa close this?
