### ISSUE TITLE
Add maintainers/contributors to Netlify team

### ISSUE THREAD

**Issue by nate-double-u** [coredns/coredns.io#281]
There are no maintainers or contributors in the Netlify team (https://app.netlify.com/sites/coredns/overview). 

We should make sure that there are some folks from the project on the Netlify team in case further changes need to be made.

_Originally posted by @nate-double-u in https://github.com/coredns/coredns.io/issues/277#issuecomment-1324413990_

**Comment by chrisohaver** [comment]
Ok. How do we do that?

**Comment by gaby** [comment]
@nate-double-u @chrisohaver Any updates on this? The website needs an update asap. 😁

**Comment by nate-double-u** [comment]
Sorry, i missed @chrisohaver's message.

@gaby, @chrisohaver, please send me the email addresses of the folks who should have Netlify access (either here, or dm me in the CNCF slack).

Builds should be working now that #277 has been completed -- please let me know if this isn't the case. This issue is just about setting things up moving forward.

**Comment by nate-double-u** [comment]
closing as @chrisohaver has accepted an invite. Thanks Chris!
