### ISSUE TITLE
Switching coredns.io over to netlify

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns.io#285]
We should cut coredns.io over netlify.

Do any CoreDNS maintainers have access/control of coredns.io to update DNS to point to netlify?

**Comment by chrisohaver** [comment]
What do we need to do to make this happen?  Our chronically out of date website is confusing the community.

**Comment by johnbelamaric** [comment]
It's working for me:

![image](https://user-images.githubusercontent.com/9468083/226354154-3363dae4-bdf1-40fb-9f40-a94d742e39f7.png)

**Comment by chrisohaver** [comment]
hmmm

```
% curl https://coredns.io/      
Redirecting to https://about.coredns.io/
```

**Comment by chrisohaver** [comment]
I guess the redirect changes have not been propagated to all netlify servers yet.

**Comment by chrisohaver** [comment]
Working now. yay!
