### ISSUE TITLE
CoreDNS [ERROR] plugin/errors: 2 . Unable to reach internet from inside the pod

### ISSUE THREAD

**Issue by parshva-shah-dsw** [coredns/coredns.io#294]
K8s :- V1.26.1
OS : - RHEL 8.7
VM is hosted using Azure cloud provider.

![image](https://github.com/coredns/coredns.io/assets/117802398/faf19d01-0fcc-44d7-9dd5-6d66a26e8a76)

Core dns logs :-
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34391->168.63.129.16:53: read: no route to host
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:34275->168.63.129.16:53: read: no route to host
[ERROR] plugin/errors: 2 2568389657905608835.8295431261288812352. HINFO: read udp 192.168.54.66:59435->168.63.129.16:53: read: no route to host

Unable to reach internet from inside the pod. nslookup fails with below error

<img width="269" alt="image" src="https://github.com/projectcalico/calico/assets/117802398/a9e16b9e-093d-4320-8b2d-6441ffc96694">

**Comment by zouyee** [comment]
Regarding issues related to CoreDNS, please submit them under the https://github.com/coredns/coredns/issues 
/close
