### ISSUE TITLE
Manual sections empty for Kubernetes, Metrics, Caching

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns.io#87]
There are quite a few empty sections on the manual document:

> ![image](https://user-images.githubusercontent.com/159209/40281349-84c2f99a-5c15-11e8-88de-1f1bca298d37.png)

**Comment by chrisohaver** [comment]
Aside from what is in the README of each plugin, what would you like to see here?
Perhaps we can improve the plugin READMEs if they are lacking.

**Comment by ahmetb** [comment]
Empty sections don't help with the documentation.

Currently in this "manual" doc, some plugins are summarized. Maybe summarize these and link to their README, OR just omit them from the list?

**Comment by miekg** [comment]
removed
