### ISSUE TITLE
Difference between forward and proxy plugins is unclear

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns.io#88]
https://coredns.io/manual/toc/#forwarding says:

> We currently have two plugins that allow for this, `proxy` and `forward`.

I read both https://coredns.io/plugins/forward/ and https://coredns.io/plugins/forward/ and the difference is still unclear to me. Their specs look almost identical. 

I think the best way to help users decide would be:

- in each plugin doc, refer to the other one and tell the difference
- in /manual/toc/#forwarding , explain the difference

Unfortunately I cannot contribute to this as I am still trying to figure out the answer myself.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns.io] Difference bet..." ]
>https://coredns.io/manual/toc/#forwarding says:
>
>> We currently have two plugins that allow for this, `proxy` and `forward`.
>
>I read both https://coredns.io/plugins/forward/ and https://coredns.io/plugins/forward/ and the difference is still unclear to me. Their specs look almost identical.
>
>I think the best way to help users decide would be:
>
>- in each plugin doc, refer to the other one and tell the difference
>- in /manual/toc/#forwarding , explain the difference
>
>Unfortunately I cannot contribute to this as I am still trying to figure out the answer myself.

+1

At some point proxy should be deprecated. The google_https protocol is already 
on the chopping block for 1.1.3.

Functional; the proxy plugin supports more protocols than forward.

**Comment by miekg** [comment]
The proxy plugin has been moved to coredns/proxy , thereby - technically - negating this issue. Closing as such.
