### ISSUE TITLE
Republish the site

### ISSUE THREAD

**Issue by ahmetb** [coredns/coredns.io#89]
I was reading https://coredns.io/plugins/proxy/ but I found some typos, which are fixed over 24 days ago. I believe the changes have not been republished. Opening an issue to point this out, treat as low-priority.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns.io] Republish the ..." ]
>I was reading https://coredns.io/plugins/proxy/ but I found some typos, which are fixed over 24 days ago. I believe the changes have not been republished. Opening an issue to point this out, treat as low-priority.

Ack, these get pushed up on a new coredns, not pulled automatically; sometimes 
there are incompat changes.

Ideally we should version this per coredns release, but that requires some work.
