### ISSUE TITLE
Longest suffix match description

### ISSUE THREAD

**Issue by albatross0** [coredns/coredns.io#93]
https://github.com/coredns/coredns.io/blob/master/content/manual/plugins.md#L9-12

> 1. If there are multiple Servers configured that listen on the queried port, it will check which one
>    has the most specific zone for this query (longest suffix match). E.g. if there are two Servers,
>    one for `example.org` and one for `a.example.org`, and the query is for `www.b.example.org`, it
>    will be routed to the latter.

The query of `www.b.example.org` will be routed to the former.
I guess the query is for `www.a.example.org` .

**Comment by miekg** [comment]
fixed in 67a56533
